### ISSUE TITLE
加个

### ISSUE THREAD

**Issue by luhux** [rpisystem/RPiSystem.github.io#1]
来加一个:

rpi3 64 位的 gentoo  非 gentoo 官方

https://gitee.com/luhux/raspberrypi3arm64gentoo

zerow 的 gentoo  非 gentoo 官方

https://gitee.com/luhux/raspberrypizerowarmv6hardfpgentoo

rpi3 的 slackwarearm , sarpi 提供 (唯一提供安装盘界面的树梅派系桶)

http://rpi.fatdog.eu/index.php?p=downloads 

rpi3 64 位的 parrotsec  非官方:

https://parrotsec-cn.org/t/3-64-parrotsec/2275

**Comment by YuzukiTsuru** [comment]
![$SINIP04NZ0ZE@TR 6LV3H6](https://user-images.githubusercontent.com/12003087/54974435-fee83980-4fce-11e9-87fc-e92c34dc025b.gif)
麻烦pull request的方法加系统哦，最近真的忙不过来了
