### ISSUE TITLE
被Safari识别为欺骗性网站

### ISSUE THREAD

**Issue by hmsjy2017** [rpisystem/RPiSystem.github.io#5]
如图
![7C9279AD-9248-45A6-B957-A416F5E1277A](https://user-images.githubusercontent.com/42692274/107912972-83b11780-6f9a-11eb-8045-b183dd45581f.png)

**Comment by YuzukiTsuru** [comment]
rpios.top 这个域名之前被用于欺诈行为，此域名已到期，目前将更换域名使用。

Sent With Hyper H
